### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by MuhRandy** [MuhRandy/battleship#1]
- [ ] Implement drag and drop to allow players to place their ships.
- [ ] Create a 2-player option that lets users take turns by passing the laptop back and forth, or by spinning the monitor around on a desktop. Implement a ‘pass device’ screen so that players don’t see each other’s boards!
- [ ] Polish the intelligence of the computer player by having it try adjacent slots after getting a ‘hit’.
